name: C++ Linter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: Install dependencies & package
      run: |
        python -m pip install --upgrade pip
        python -m pip install cpplint
    - name: Lint with cpplint
      run: |
        cpplint --recursive --linelength=120 --filter=-legal/copyright,-build/include_subdir,-build/c++11,-build/namespaces .
